version: '3.8'
services:
  javaapp:
   build: .
   ports:
     - 8080
     networks:
       - javanetwork

  dotnetapp:
    build: 
      context: dotnetapp
      dockerfile: ../.dockerdotnetfile
    ports:
      - 5000
  pythonapp:
    build: .
    ports:
      - 5001
  nodejsapp
    build: .
    ports:
      -80

version: '3.8'

services:
  nginxapp:
    image: nginx:1.29
    ports:
      -80
  jenkinsapp:
    image: jenkins/jenkins
    ports:
      -8080

